name: Android CI & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build, Analyze & Release APK/AAB/APKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Inject gradle.properties with AndroidX support
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      - name: Enable Gradle Build Scan and Project Reports
        run: |
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.configureondemand=true" >> gradle.properties
          echo "org.gradle.daemon=true" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "gradle.enterprise.buildScan.termsOfServiceUrl=https://gradle.com/terms-of-service" >> gradle.properties
          echo "gradle.enterprise.buildScan.termsOfServiceAgree=YES" >> gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintReportDebug lintReportRelease

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Generate HTML Reports
        run: |
          ./gradlew projectReport
          cp -r build/reports update.html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Analysis-Reports
          path: |
            app/build/reports/**
            update.html

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Debug
          path: app/build/outputs/apk/debug/**/*.apk

      - name: Build Release APK & Metadata
        env:
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew bundleRelease assembleRelease

      - name: Build APKS using bundletool
        run: |
          wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar -O bundletool.jar
          java -jar bundletool.jar build-apks \
            --bundle=app/build/outputs/bundle/release/app-release.aab \
            --output=app-release.apks \
            --ks=${{ secrets.RELEASE_STORE_FILE }} \
            --ks-pass=pass:${{ secrets.RELEASE_STORE_PASSWORD }} \
            --ks-key-alias=${{ secrets.RELEASE_KEY_ALIAS }} \
            --key-pass=pass:${{ secrets.RELEASE_KEY_PASSWORD }} \
            --mode=universal

      - name: Upload AAB, APKS, APK & Metadata
        uses: actions/upload-artifact@v4
        with:
          name: App-Release
          path: |
            app/build/outputs/apk/release/**/*.apk
            app/build/outputs/bundle/release/*.aab
            app-release.apks
            app/build/outputs/apk/release/output-metadata.json
            app/build/outputs/mapping/release/mapping.txt

      - name: Obfuscate, Encrypt and Optimize (Proguard/R8)
        run: |
          echo "Ensure your proguard-rules.pro includes:"
          echo "-keep class !**.BuildConfig { *; }"
          echo "-printmapping mapping.txt"
          echo "-optimizations code/simplification/arithmetic"

      - name: Upload All Project Files (Backup)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Full-Project-Backup
          path: |
            .
            !**/build/**
            !**/.gradle/**
