name: AndroidBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      # Step 2: Setup JDK (Java 17 is stable and recommended for Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies and wrapper
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Step 4: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 5: Build the APK using optimized Gradle flags
      - name: Build Debug APK
        run: ./gradlew assembleDebug --parallel --configuration-cache --no-daemon

      # Step 6: Upload the APK as an artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidRelease.apk
          path: app/build/outputs/apk/debug/app-debug.apk
