name: ANDROID CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: LintReports
          path: app/build/reports/lint-results-*.html

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Enable Gradle Build Scan (TOS accepted)
        run: echo "gradle.enterprise.buildScan.termsOfServiceUrl=https://gradle.com/terms-of-service\ngradle.enterprise.buildScan.termsOfServiceAgree=YES" > gradle.properties

      - name: Build Debug APK with Build Scan
        run: ./gradlew assembleDebug --scan

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidDebug.apk
          path: app/build/outputs/apk/debug/**/*.apk

      - name: Build Release APK
        env:
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease --scan

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidRelease.apk
          path: app/build/outputs/apk/release/**/*.apk

      - name: Upload ProGuard Mapping (if exists)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ProGuardMapping
          path: app/build/outputs/mapping/release/mapping.txt
