name: Android Release

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    env:
      VERSION_NAME: "1.0"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Configure Gradle
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -XX:+UseParallelGC" >> gradle.properties
          echo "android.enableR8.fullMode=true" >> gradle.properties

      - name: Grant Execute Permission
        run: chmod +x ./gradlew

      - name: Build Release APK
        env:
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Rename APK File
        run: |
          mkdir -p release-artifacts
          cp app/build/outputs/apk/release/*.apk release-artifacts/Ktimaz_Studio_Release_v${{ env.VERSION_NAME }}.apk

      - name: Check Last Release Date
        id: release_check
        run: |
          LAST=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.published_at // empty')
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "last_release=$LAST" >> $GITHUB_ENV
          echo "now=$NOW" >> $GITHUB_ENV
          if [[ -z "$LAST" ]]; then
            echo "ready=true" >> $GITHUB_OUTPUT
          else
            DAYS=$(python3 -c "from datetime import datetime; print((datetime.strptime('$NOW','%Y-%m-%dT%H:%M:%SZ') - datetime.strptime('$LAST','%Y-%m-%dT%H:%M:%SZ')).days)")
            echo "ready=$([[ $DAYS -ge 7 ]] && echo true || echo false)" >> $GITHUB_OUTPUT
          fi

      - name: Publish GitHub Release
        if: steps.release_check.outputs.ready == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: "KTIMAZ Studio v${{ env.VERSION_NAME }}"
          tag_name: "v${{ env.VERSION_NAME }}-${{ github.run_number }}"
          files: release-artifacts/*.apk
            # app/build/outputs/apk/release/output-metadata.json
            # app/build/outputs/mapping/release/mapping.txt
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
